"""Generate the committed markdown reports from the metrics artifacts.

Every figure in `reports/` is read from a `metrics/*.json` file. None is typed
here, which is what makes "the report matches the code" checkable with `git diff`
rather than asserted: delete `reports/`, rerun, and the files come back identical.

The synthetic caveat is emitted through `athar.provenance.markdown_caveat`, so the
sentence in a report and the sentence on the dashboard cannot drift apart.

Run: `make reports`
"""

import json
import logging
from statistics import median

from athar import paths
from athar.provenance import markdown_caveat

logging.basicConfig(level=logging.INFO, format="%(message)s")
log = logging.getLogger("render_reports")

HEADER = (
    "MAIB AI 208 · SP Jain School of Global Management, Dubai · Krishna Mathur\n\n"
    "Generated by `scripts/render_reports.py` from the artifacts in `metrics/`. "
    "Every number below is read from one of them; none is typed.\n"
)


#: Readable names for the channels. The keys are what the configuration and the
#: artifacts use; these are what a reader should see.
LABELS = {
    "search_brand": "Brand search",
    "search_nonbrand": "Non-brand search",
    "social_paid": "Paid social",
    "display_prog": "Programmatic display",
    "video_ctv": "Video / CTV",
}


def label(channel):
    return LABELS.get(channel, channel)


#: A quantity that could not be computed is written as null in the artifact, with
#: the reason beside it. These render that as an absence rather than as a zero,
#: because a zero would be a claim.
def money(value):
    return f"{value:,.2f}" if value is not None else "not computable"


def share(value):
    return f"{value:.2%}" if value is not None else "not computable"


def number(value):
    return f"{value:.3f}" if value is not None else "not computable"


def load(name):
    path = paths.metrics_dir() / f"{name}.json"
    return json.loads(path.read_text()) if path.exists() else None


def table(rows, columns, formats=None):
    """Render a markdown table, right-aligning everything but the first column."""
    formats = formats or {}
    head = "| " + " | ".join(columns) + " |"
    rule = "|" + "---|" + "---:|" * (len(columns) - 1)
    body = []
    for row in rows:
        cells = []
        for index, column in enumerate(columns):
            value = row.get(column, "")
            formatter = formats.get(column)
            cells.append(formatter(value) if formatter and value != "" else str(value))
            if index == 0:
                cells[-1] = f"**{cells[-1]}**" if False else cells[-1]
        body.append("| " + " | ".join(cells) + " |")
    return "\n".join([head, rule, *body])


def data_quality():
    frame = load("frame")
    if not frame:
        return None
    window, totals, geo = frame["window"], frame["totals"], frame["geo_panel"]
    repeat = frame["repeat_behaviour"]
    verification = frame["verification"]
    return f"""# ATHAR — the frame, and the window chosen by rule

{HEADER}
## The window

`{window["start"]}` to `{window["end"]}` — **{window["weeks"]} weeks**, none of them empty.

{window["rule"]}

Revenue is {window["revenue_definition"].lower()} Cancelled and unavailable orders
are excluded; in-flight ones are kept, because an order that is merely invoiced at
the end of the extract is a real purchase a real campaign could have caused, and
dropping it would bias the most recent weeks downward precisely where the series is
thinnest.

| | In window | All dates | Share kept |
|---|---:|---:|---:|
| Orders | {totals["orders"]:,} | {frame["coverage"]["orders_all_dates"]:,} | {frame["coverage"]["share_of_orders_in_window"]:.4f} |
| Revenue (BRL) | {totals["revenue_brl"]:,.2f} | {frame["coverage"]["revenue_all_dates_brl"]:,.2f} | {frame["coverage"]["share_of_revenue_in_window"]:.4f} |

Mean order value {totals["mean_order_value_brl"]:,.2f} BRL across {totals["people"]:,}
people in {totals["states"]} states.

## Verification

`athar.frame` stages its join through CTEs; the check in `scripts/build_frame.py`
uses a flat join and filter and shares no code path. They agree on the order count
exactly and on revenue to {verification["independent_revenue_relative_difference"]:.2e}
relative — {verification["independent_revenue_difference_brl"]:.2e} BRL on 1.3e7.

They cannot agree bit-for-bit and it would be wrong to require it. Float addition is
not associative, the two query plans accumulate {totals["orders"]:,} terms in
different orders, and DuckDB is already pinned to a single thread. So the test is
agreement to the centavo — the resolution the quantity actually has — with the raw
difference recorded so a reader can see how far inside tolerance it sits.

| Check | Result |
|---|---:|
| Independent order count matches | {verification["independent_order_count_matches"]} |
| Revenue difference (BRL) | {verification["independent_revenue_difference_brl"]:.2e} |
| Tolerance (BRL) | {verification["independent_revenue_tolerance_brl"]} |
| Zero-order weeks inside the window | {verification["zero_order_weeks_in_window"]} |

## The geography, and the power problem it creates

{geo["states"]} states, a balanced panel of {geo["rows"]:,} state-weeks. One state
carries {geo["largest_state_revenue_share"]:.1%} of revenue and
{geo["states_below_one_percent_of_revenue"]} of the {geo["states"]} carry under 1%
each. That concentration is what makes a geo holdout expensive, and it is Olist's
rather than this project's invention — `reports/experiments.md` measures the
consequence.

## The repeat rate, which decides the lifetime-value work

A person is `customer_unique_id`. Olist issues a fresh `customer_id` per order, so
keying on that would report a repeat rate of exactly zero.

| Basis | People | With a repeat | Repeat rate |
|---|---:|---:|---:|
| All dates | {repeat["all_dates"]["people"]:,} | {repeat["all_dates"]["with_repeat"]:,} | {repeat["all_dates"]["repeat_rate"]:.4f} |
| In window | {repeat["in_window"]["people"]:,} | {repeat["in_window"]["with_repeat"]:,} | {repeat["in_window"]["repeat_rate"]:.4f} |

{repeat["in_window"]["with_two_or_more_repeats"]:,} customers bought more than twice.
`reports/clv.md` takes that seriously rather than working around it.
"""


def panel_report():
    panel = load("panel")
    if not panel:
        return None
    design, ident = panel["design"], panel["identification"]
    channels = panel["channels"]
    rows = "\n".join(
        f"| {label(c['channel'])} | {c['mean_weekly_spend']:,.0f} | {c['true_roi_average']:.2f} | "
        f"{c['true_roi_marginal']:.2f} | {c['marginal_over_average']:.2f} | "
        f"{c['adstock_theta']:.0f} | {c['lastclick_roas']:.2f} | "
        f"{c['lastclick_bias_relative']:+.1%} |"
        for c in channels
    )
    return f"""# ATHAR — the instrument: a panel whose truth is known

{HEADER}
{markdown_caveat(panel)}## Why a simulated panel at all

No real advertiser knows the true ROI of its own media plan. That is the difficulty
the field is organised around, and it means "did the model recover the truth?"
cannot be asked of real data. It is asked here instead, of a panel built from
`config/dgp.yaml`, committed before any model was fitted.

Configuration `{panel["provenance"]["dgp_hash"]}`, seed `{panel["provenance"]["seed"]}`.

## The design

{design["weeks"]} weeks on the real Olist revenue baseline. Total spend
{design["total_spend"]:,.0f} BRL, {design["spend_as_share_of_revenue"]:.1%} of revenue;
simulated media contributes {design["media_as_share_of_revenue"]:.1%} of it at a
blended true ROI of {design["blended_true_roi"]:.2f}.

| Channel | Weekly spend | True avg ROI | True marginal | Marginal/avg | Adstock peak (wks) | Last-click ROAS | Error |
|---|---:|---:|---:|---:|---:|---:|---:|
{rows}

**Average ROI is not marginal ROI, and which is larger is not fixed.** A Hill curve
with a slope above one is S-shaped: below its inflection the response is convex,
marginal exceeds average, and the channel is under-invested. Above it the curve is
concave and marginal falls below average. Both regimes are present here, which is
what makes the allocation in `reports/triangulation.md` a decision rather than a
ranking.

## The deliberate misspecification

- **Generated with**: {design["collinearity_level"]} collinearity, {panel["generating_specification"]["adstock"]}, {panel["generating_specification"]["saturation"]} saturation.
- **Fitted with**: {panel["generating_specification"]["fitted_with"]}

A practical note that shaped the design. The kernel was originally a Weibull PDF.
`WeibullPDFAdstock` raises `TypeError: x must be have an XTensorType` under
pymc-marketing 0.19.2 with pytensor 2.38.2, for every saturation, so the matched arm
could not be fitted at all. `WeibullCDFAdstock` samples cleanly but its kernel is a
survival curve and decays monotonically, so it cannot represent a delayed peak
either. The delayed-geometric form both admits a delayed peak and can be fitted,
which is what makes the matched arm genuinely matched rather than merely close.

## How hard the identification problem is

| Diagnostic | Value |
|---|---:|
| Max pairwise spend correlation | {ident["max_pairwise_correlation"]:.3f} |
| Condition number | {ident["condition_number"]:.2f} |
| Max VIF | {ident["max_vif"]:.2f} |
| Media share of revenue variance (raw) | {ident["media_share_of_revenue_variance"]:.3f} |
| Media share of **detrended** variance | {ident["media_share_of_detrended_variance"]:.3f} |

{ident["note"]}

## Attribution, and its one pre-registered knob

{panel["attribution_summary"]["mechanism"]}

{panel["attribution_summary"]["null_case"]}

Most overstated: **{label(panel["attribution_summary"]["most_overstated"])}**.
Most understated: **{label(panel["attribution_summary"]["most_understated"])}**.
"""


def criteo_report():
    criteo = load("criteo")
    uplift = load("uplift")
    if not criteo:
        return None
    itt, gap = criteo["intent_to_treat"], criteo["platform_reported_versus_incremental"]
    naive, cace = gap["naive_rate_framing"], criteo["complier_effect"]
    conversion, effective = criteo["conversion"], criteo["effective_sample"]

    uplift_section = "`metrics/uplift.json` not present.\n"
    if uplift:
        rows = "\n".join(
            f"| {name} | {result['qini']:.5f} | {result['ci_low']:.5f} | "
            f"{result['ci_high']:.5f} | {'yes' if result['beats_random'] else 'no'} |"
            for name, result in sorted(uplift["models"].items(), key=lambda kv: -kv[1]["qini"])
        )
        verdict = uplift["verdict"]
        uplift_section = f"""Four learners and a random-targeting baseline, scored by Qini on a held-out half
with a 95% bootstrap interval. {uplift["evaluation"]["why"]}

Test half carries {uplift["sample"]["test_control_converters"]:,} control-arm
converters, which is what bounds the precision below — not the
{uplift["sample"]["test_rows"]:,} rows.

| Model | Qini | CI low | CI high | Beats random |
|---|---:|---:|---:|---|
{rows}

Best model: **{verdict["best_model"]}** at {verdict["best_qini"]:.5f}.
Any model beats random: **{verdict["any_model_beats_random"]}**.

{uplift["evaluation"]["exposure_note"]}
"""

    return f"""# ATHAR — Criteo: the real causal result

{HEADER}
This is the only result in ATHAR whose causal claim rests on data rather than on a
construction. Criteo-UPLIFT v2.1 is a genuine randomised trial over
{criteo["population"]["rows"]:,} users, {criteo["population"]["treated_share"]:.0%}
of them eligible to be shown advertising.

**{criteo["randomisation_check"]["exposure_in_control_arm"]} exposures leaked into the
control arm**, so the randomisation is clean and `exposure` is unambiguously
post-treatment.

## The intent-to-treat effect

| | Rate | 95% interval |
|---|---:|---|
| Treated | {conversion["treated_rate"]:.6f} | {conversion["treated_ci"][0]:.6f} – {conversion["treated_ci"][1]:.6f} |
| Control | {conversion["control_rate"]:.6f} | {conversion["control_ci"][0]:.6f} – {conversion["control_ci"][1]:.6f} |

Absolute lift **{itt["absolute_lift"]:.8f}** (95% CI {itt["ci_95"][0]:.8f} –
{itt["ci_95"][1]:.8f}), a relative lift of {itt["relative_lift"]:.1%}, or
{itt["incremental_conversions"]:,.0f} incremental conversions.

## What a platform reports, against what happened

| | Value |
|---|---:|
| Platform-reported conversions | {gap["platform_reported_conversions"]:,} |
| Incremental conversions | {gap["incremental_conversions"]:,.0f} |
| **Overstatement** | **{gap["overstatement_ratio"]}×** |

Stated as a rate rather than a count, the same trial reads very differently:

| | Value |
|---|---:|
| Conversion rate among the exposed | {naive["conversion_rate_among_exposed"]:.6f} |
| Conversion rate in control | {naive["conversion_rate_in_control"]:.6f} |
| Naive rate ratio | {naive["naive_rate_ratio"]}× |
| True intent-to-treat ratio | {naive["true_relative_lift_ratio"]}× |

Both are correct arithmetic on the same trial. Only
{naive["exposed_share_of_treated_arm"]:.1%} of the treated arm was ever exposed, so a
roughly seventeen-fold exaggeration of the *rate* becomes a
{gap["overstatement_ratio"]}× exaggeration of the *count*. Reporting only the
dramatic framing would be rhetoric rather than a finding, so both are here.

## The defensible version of "effect on the exposed"

Random assignment as an instrument for exposure: a complier effect of
**{cace["cace"]:.6f}** (95% CI {cace["ci_95"][0]:.6f} – {cace["ci_95"][1]:.6f}) at a
compliance rate of {cace["compliance_rate"]:.4f}.

{cace["interpretation"]}

## Is the effect findable

{uplift_section}
## Effective sample size

{effective["distinct_feature_vectors"]:,} distinct feature vectors from
{criteo["population"]["rows"]:,} rows ({effective["distinct_share"]:.3f}).

{effective["note"]}
"""


def recovery_report():
    recovery = load("recovery")
    mmm = load("mmm")
    if not recovery and not mmm:
        return None

    headline = ""
    if mmm:
        blocks = []
        for name, fit in mmm["fits"].items():
            summary = fit["average_roi"]["summary"]
            diagnostics = fit["diagnostics"]
            rows = "\n".join(
                f"| {label(channel)} | {entry['true']:.2f} | {entry['estimated_mean']:.2f} | "
                f"{entry['hdi_low']:.2f} – {entry['hdi_high']:.2f} | "
                f"{'yes' if entry['covered'] else '**no**'} | {entry['relative_error']:+.1%} |"
                for channel, entry in fit["average_roi"]["channels"].items()
            )
            blocks.append(f"""### {name}

{mmm["design"]["specifications"][name]}

Sampler: {diagnostics["divergences"]} divergences in
{diagnostics["post_warmup_draws"]} draws ({diagnostics["divergence_rate"]:.3%}), max
R-hat {diagnostics["max_r_hat"]}, min bulk ESS {diagnostics["min_ess_bulk"]} —
**{"converged" if diagnostics["passed"] else "failed its diagnostics"}**.

| Channel | True | Estimate | 89% interval | Covered | Error |
|---|---:|---:|---:|---|---:|
{rows}

Coverage {summary["channels_covered"]}/{summary["channels_total"]}, median absolute
relative error {summary["median_absolute_relative_error"]:.1%}, mean interval width
{summary["mean_interval_width"]:.2f}.
""")
        headline = "\n".join(blocks)

    grid = ""
    if recovery:
        rows = []
        for name, slice_ in sorted(recovery["slices"].items()):
            block = slice_["average_roi"]
            if not block.get("converged"):
                rows.append(f"| {name} | 0 | — | — | — |")
                continue
            rows.append(
                f"| {name} | {block['converged']}/{block['fits']} | "
                f"{block['coverage_rate']:.2f} | "
                f"{block['median_absolute_relative_error']:.2f} | "
                f"{block['mean_interval_width']:.2f} |"
            )
        convergence = recovery["convergence"]

        # Every claim below is computed from the fitted cells and emitted only if
        # the numbers point that way. A narrative written in advance and left to
        # stand whatever the data said would be the opposite of this project's
        # point, so each one is gated on its own direction check.
        fits = [f for f in recovery["fits"] if f["diagnostics"]["passed"]]
        claims = []

        def cell(spec, collinearity, weeks, key="average_roi"):
            chosen = [
                f[key]["summary"]
                for f in fits
                if f["specification"] == spec
                and f["collinearity"] == collinearity
                and f["weeks"] == weeks
            ]
            if not chosen:
                return None
            return {
                "n": len(chosen),
                "coverage": median([c["coverage_rate"] for c in chosen]),
                "error": median([c["median_absolute_relative_error"] for c in chosen]),
                "width": median([c["mean_interval_width"] for c in chosen]),
            }

        by_spec = {}
        for fit in fits:
            by_spec.setdefault(fit["specification"], []).append(fit["average_roi"]["summary"])

        if {"matched", "misspecified"} <= set(by_spec):
            m = by_spec["matched"]
            x = by_spec["misspecified"]
            m_cov, x_cov = (
                median([c["coverage_rate"] for c in m]),
                median([c["coverage_rate"] for c in x]),
            )
            m_err, x_err = (
                median([c["median_absolute_relative_error"] for c in m]),
                median([c["median_absolute_relative_error"] for c in x]),
            )
            m_wide, x_wide = (
                median([c["mean_interval_width"] for c in m]),
                median([c["mean_interval_width"] for c in x]),
            )
            if m_cov >= x_cov and m_err > x_err and m_wide > x_wide:
                claims.append(
                    f"**Fitting the right functional form made the answer worse.** The "
                    f"matched arm — the one handed the shape that generated the data — "
                    f"reaches higher coverage ({m_cov:.2f} against {x_cov:.2f}) and is "
                    f"nonetheless {m_err / x_err:.0f} times further from the truth, with a "
                    f"median relative error of {m_err:.2f} against {x_err:.2f} and intervals "
                    f"{m_wide / x_wide:.0f} times wider. It has more parameters to identify "
                    f"— a decay and a delay, a slope and a half-saturation point — from the "
                    f"same weak signal, so it pins none of them down and covers the truth by "
                    f"being unable to exclude anything. This is the clearest argument in the "
                    f"project against reading coverage on its own, and it points the "
                    f"opposite way from the obvious expectation that the "
                    f"correctly-specified model should win."
                )

        counts = {}
        for fit in recovery["fits"]:
            entry = counts.setdefault(fit["specification"], [0, 0])
            entry[0] += 1
            entry[1] += int(fit["diagnostics"]["passed"])
        if {"matched", "misspecified"} <= set(counts):
            mt, mc = counts["matched"]
            xt, xc = counts["misspecified"]
            if mc / mt < xc / xt:
                claims.append(
                    f"**And it was harder to fit at all.** The matched arm passed its "
                    f"sampler diagnostics in {mc} of {mt} runs against {xc} of {xt} for the "
                    f"misspecified one. The extra parameters do not only widen the interval; "
                    f"they make the posterior geometry hard enough that the sampler often "
                    f"cannot explore it. A practitioner who reached for the more flexible "
                    f"model would spend the time and end up with fewer usable fits."
                )

        for collinearity in ("high", "low"):
            short, long = (
                cell("misspecified", collinearity, 85),
                cell("misspecified", collinearity, 156),
            )
            if not (short and long):
                continue
            if long["coverage"] < short["coverage"] and long["width"] < short["width"]:
                claims.append(
                    f"**More data made coverage worse.** For the misspecified model at "
                    f"{collinearity} collinearity, going from 85 to 156 weeks moved coverage "
                    f"from {short['coverage']:.2f} to {long['coverage']:.2f} while the "
                    f"intervals narrowed from {short['width']:.2f} to {long['width']:.2f}. "
                    f"That is what a misspecified model does with more evidence: it becomes "
                    f"more confident about the wrong value. Length helps a model that could "
                    f"have been right and hurts one that could not — which is worth knowing "
                    f"before waiting a year to collect more history."
                )
                break

        narrative = (
            "\n\n".join(claims)
            if claims
            else "No claim here survived a check against the fitted cells."
        )
        grid = f"""## The recovery grid

{convergence["fits"]} full-posterior fits: {" × ".join(str(x) for x in recovery["design"]["panel_lengths"])} weeks,
{" and ".join(recovery["design"]["collinearity_levels"])} collinearity, both
specifications, {len(recovery["design"]["seeds"])} seeds.
{convergence["converged"]} converged and are included;
{convergence["failed"]} failed their diagnostics and are excluded and counted rather
than averaged in.

{recovery["design"]["baseline"]}

{recovery["design"]["priors"]}

| Cell | Converged | Coverage | Median abs rel error | Mean interval width |
|---|---:|---:|---:|---:|
{chr(10).join(rows)}

**Coverage alone is not enough.** An interval achieves perfect coverage by being
uselessly wide, so width is reported beside it. A cell with coverage 1.00 and a
median error above 1.0 has not recovered anything; it has declined to answer.

{convergence["rule_note"]}

## What the grid shows

{narrative}
"""

    return f"""# ATHAR — did the media-mix model recover the truth

{HEADER}
{markdown_caveat(mmm or recovery)}## The headline fits

{headline}
{grid}"""


def experiments_report():
    experiments = load("experiments")
    if not experiments:
        return None
    geography, design = experiments["geography"], experiments["design"]
    blocks = []
    for channel, curve in experiments["power"].items():
        rows = "\n".join(
            f"| {row['treated_states']} | {row['median_treated_revenue_share']:.1%} | "
            f"{row['median_relative_error']:+.3f} | {row['relative_error_sd']:.2f} | "
            f"{row['detected']:.0%} |"
            for row in curve
        )
        blocks.append(f"""### {label(channel)}

| Treated states | Revenue switched off | Median error | Error SD | Detected |
|---|---:|---:|---:|---:|
{rows}
""")
    return f"""# ATHAR — geo holdout tests: unbiased, imprecise, expensive

{HEADER}
{markdown_caveat(experiments)}## The geography is real

{geography["states"]} Brazilian states. The largest carries
{geography["largest_state_share"]:.1%} of revenue; the top five carry
{geography["top_five_share"]:.1%}; {geography["states_below_one_percent"]} carry under
1% each. Source: {geography["source"]}.

## Design

A {design["test_weeks"]}-week holdout, {design["estimator"]},
{design["replicates_per_point"]} random assignments of treated states per point.

"Detected" means {design["detected_criterion"]}

{design["assumption"]}

## Results

{"".join(blocks)}
## What this costs

{experiments["cost"]["note"]}
"""


def clv_report():
    clv = load("clv")
    if not clv:
        return None
    behaviour, ml = clv["repeat_behaviour"], clv["maximum_likelihood"]
    value, validation = clv["lifetime_value"], clv["validation"]
    bayesian = clv["models"]["bgnbd_bayesian_full_base"]
    sampler = bayesian["parameters"].get("sampler", {})
    degenerate = bayesian.get("degenerate_parameters", [])
    return f"""# ATHAR — customer lifetime value, and a model that does not fit

{HEADER}
## The base

{behaviour["repeat_rate"]:.2%} of {behaviour["customers"]:,} customers ever bought
twice. Those who did averaged {behaviour["mean_repeats_among_repeaters"]:.2f} repeat
purchases; {behaviour["with_two_or_more_repeats"]:,} bought more than twice.

## Maximum likelihood does not converge

| Basis | Settings attempted | Converged |
|---|---:|---:|
| Full base | {len(ml["attempts_full_base"])} | {ml["converged_on_full_base"]} |
| Repeaters only | {len(ml["attempts_repeaters_only"])} | {ml["converged_on_repeaters_only"]} |

Across days, weeks and months, at penalties from 0 to 10.

{ml["finding"]}

## The Bayesian fit runs, and should not be believed either

Fitted on {bayesian["fitted_on"]:,} customers of {bayesian.get("available", 0):,} —
BG/NBD has four parameters, and sampling it over the whole base costs an hour
without changing them.

| | Value |
|---|---:|
| Divergences | {sampler.get("divergences", "n/a")} |
| Max R-hat | {sampler.get("max_r_hat", "n/a")} |
| Min bulk ESS | {sampler.get("min_ess_bulk", "n/a")} |
| Sampler passed | **{sampler.get("passed", "n/a")}** |
| Degenerate parameters | {", ".join(degenerate) if degenerate else "none"} |
| Fit trustworthy | **{bayesian.get("trustworthy", "n/a")}** |

{bayesian["note"]}

## Verdict

{clv.get("verdict", "")}

## Validation on a time-based holdout

{validation["holdout_weeks"]}-week holdout ending {validation["observation_end"]},
{validation["customers"]:,} customers with history.

| | Value |
|---|---:|
| Predicted purchases | {validation["predicted_total"]:.1f} |
| Actual purchases | {validation["actual_total"]:.0f} |
| Mean absolute error | {validation["mean_absolute_error"]:.5f} |
| MAE of predicting zero | {validation["mean_absolute_error_predicting_zero"]:.5f} |
| Beats predicting zero | **{validation["beats_predicting_zero"]}** |

{validation["metric_note"]}

## What lifetime value comes to

| | Value |
|---|---:|
| Mean expected CLV over a year (BRL) | {money(value["mean_expected_clv_brl"])} |
| Mean first-order value (BRL) | {money(value["mean_first_order_value_brl"])} |
| CLV as a share of first-order value | {share(value["clv_over_first_order_value"])} |
| Correlation with first-order value | {number(value["correlation_clv_with_first_order_value"])} |

{value.get("why_not") or clv["finding"]}
"""


def triangulation_report():
    triangulation = load("triangulation")
    if not triangulation:
        return None
    headline, allocation = triangulation["headline"], triangulation["allocation"]
    comparison = triangulation["comparison"]

    def experiment_cell(entry):
        estimate = entry["experiment"].get("estimate")
        return f"{estimate:.2f}" if estimate is not None else "not run"

    rows = "\n".join(
        f"| {label(channel)} | {entry['true_roi']:.2f} | "
        f"{entry['attribution']['estimate']:.2f} | "
        f"{entry['mmm']['estimate']:.2f} | "
        f"{experiment_cell(entry)} | "
        f"{entry['divergence']:.2f} | {entry['closest_method']} |"
        for channel, entry in comparison["channels"].items()
    )
    allocations = "\n".join(
        f"| {name} | {entry['revenue_under_truth']:,.0f} | "
        f"{entry['shortfall_against_best']:,.0f} | {entry['shortfall_share']:.2%} |"
        for name, entry in sorted(
            allocation["allocations"].items(), key=lambda kv: kv[1]["shortfall_share"]
        )
    )
    clv_note = triangulation.get("clv_consequence")
    clv_section = (
        f"\n## The lifetime-value consequence\n\n{clv_note['consequence']}\n" if clv_note else ""
    )
    return f"""# ATHAR — triangulation: where the three disagree, and what that costs

{HEADER}
{markdown_caveat(triangulation)}## The three estimates

| Channel | True | Attribution | MMM | Experiment | Divergence | Closest |
|---|---:|---:|---:|---:|---:|---|
{rows}

Most divergent: **{label(comparison["summary"]["most_divergent_channel"])}**.
Least divergent: **{label(comparison["summary"]["least_divergent_channel"])}**.

{comparison["summary"]["note"]}

## Turning each into a budget

{allocation["governance"]["note"]} Floors of
{allocation["governance"]["floor_share"]:.0%} and caps of
{allocation["governance"]["cap_share"]:.0%} per channel, applied identically.

| Allocation | Revenue under truth (BRL) | Shortfall (BRL) | Shortfall |
|---|---:|---:|---:|
{allocations}

## The answer

{headline["statement"]}

{triangulation["scenario_in_aed"]["caveat"]}

{triangulation["scenario_in_aed"]["on_a_one_million_aed_budget"]["note"]}
{clv_section}
## Two method notes

{triangulation["method_notes"]["why_not_average"]}

{triangulation["method_notes"]["linear_versus_curved"]}
"""


REPORTS = {
    "data_quality": data_quality,
    "panel": panel_report,
    "criteo": criteo_report,
    "recovery": recovery_report,
    "experiments": experiments_report,
    "clv": clv_report,
    "triangulation": triangulation_report,
}


def main():
    directory = paths.reports_dir()
    written = 0
    for name, builder in REPORTS.items():
        content = builder()
        if content is None:
            log.warning("skipped %s.md — its metrics artifact is not present", name)
            continue
        (directory / f"{name}.md").write_text(content.rstrip() + "\n")
        log.info("wrote reports/%s.md", name)
        written += 1
    log.info("%d of %d reports written", written, len(REPORTS))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
